// album-viewer/src/App.vue
<template>
  <div class="app">
    <header class="header">
      <div class="header-content">
        <div class="header-text">
          <h1>🎵 {{ t('app.title') }}</h1>
          <p>{{ t('app.subtitle') }}</p>
        </div>
        <div class="header-actions">
          <CartIcon />
          <LanguageSelector />
        </div>
      </div>
    </header>

    <CartPanel />

    <main class="main">
      <div v-if="loading" class="loading">
        <div class="spinner"></div>
        <p>{{ t('loading.message') }}</p>
      </div>

      <div v-else-if="error" class="error">
        <p>{{ t('error.message') }}</p>
        <button @click="fetchAlbums" class="retry-btn">{{ t('error.retry') }}</button>
      </div>

      <div v-else class="albums-grid">
        <AlbumCard 
          v-for="album in albums" 
          :key="album.id" 
          :album="album" 
        />
      </div>
    </main>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useI18n } from 'vue-i18n'
import axios from 'axios'
import AlbumCard from './components/AlbumCard.vue'
import LanguageSelector from './components/LanguageSelector.vue'
import CartIcon from './components/CartIcon.vue'
import CartPanel from './components/CartPanel.vue'
import type { Album } from './types/album'

const { t } = useI18n()
const albums = ref<Album[]>([])
const loading = ref<boolean>(true)
const error = ref<string | null>(null)

const fetchAlbums = async (): Promise<void> => {
  try {
    loading.value = true
    error.value = null
    const response = await axios.get<Album[]>('/albums')
    albums.value = response.data
  } catch (err) {
    error.value = 'error'
    console.error('Error fetching albums:', err)
  } finally {
    loading.value = false
  }
}

onMounted(() => {
  fetchAlbums()
})
</script>

<style scoped>
.app {
  min-height: 100vh;
  padding: 2rem;
}

.header {
  margin-bottom: 3rem;
  color: white;
}

.header-content {
  display: flex;
  justify-content: space-between;
  align-items: center;
  max-width: 1200px;
  margin: 0 auto;
  gap: 2rem;
}

.header-text {
  text-align: center;
  flex: 1;
}

.header-actions {
  display: flex;
  align-items: center;
  gap: 1rem;
}

.header h1 {
  font-size: 3rem;
  margin-bottom: 0.5rem;
  text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.3);
}

.header p {
  font-size: 1.2rem;
  opacity: 0.9;
}

.main {
  max-width: 1200px;
  margin: 0 auto;
}

.loading {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 4rem;
  color: white;
}

.spinner {
  width: 50px;
  height: 50px;
  border: 4px solid rgba(255, 255, 255, 0.3);
  border-top: 4px solid white;
  border-radius: 50%;
  animation: spin 1s linear infinite;
  margin-bottom: 1rem;
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}

.error {
  text-align: center;
  padding: 4rem;
  color: white;
}

.error p {
  font-size: 1.2rem;
  margin-bottom: 2rem;
}

.retry-btn {
  background: rgba(255, 255, 255, 0.2);
  color: white;
  border: 2px solid white;
  padding: 0.75rem 2rem;
  border-radius: 25px;
  font-size: 1rem;
  cursor: pointer;
  transition: all 0.3s ease;
}

.retry-btn:hover {
  background: white;
  color: #667eea;
}

.albums-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
  gap: 2rem;
  padding: 1rem;
}

@media (max-width: 768px) {
  .app {
    padding: 1rem;
  }
  
  .header-content {
    flex-direction: column;
    gap: 1rem;
  }
  
  .header h1 {
    font-size: 2rem;
  }
  
  .albums-grid {
    grid-template-columns: 1fr;
    gap: 1rem;
  }
}
</style>

// album-viewer-react/src/App.tsx
/// <reference types="vite/client" />
import React, { useEffect, useState } from 'react'
import AppBar from '@mui/material/AppBar'
import Box from '@mui/material/Box'
import CircularProgress from '@mui/material/CircularProgress'
import Container from '@mui/material/Container'
import Grid from '@mui/material/Grid2'
import Toolbar from '@mui/material/Toolbar'
import Typography from '@mui/material/Typography'
import Alert from '@mui/material/Alert'
import Button from '@mui/material/Button'
import axios from 'axios'
import AlbumCard from './components/AlbumCard'
import type { Album } from './types/album'

export default function App(): React.ReactElement {
  const [albums, setAlbums] = useState<Album[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  const fetchAlbums = async (): Promise<void> => {
    setLoading(true)
    setError(null)
    try {
      const { data } = await axios.get<Album[]>('/albums')
      setAlbums(data)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to fetch albums')
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    void fetchAlbums()
  }, [])

  const bgColor = import.meta.env.VITE_BACKGROUND_COLOR as string | undefined

  return (
    <Box
      sx={{
        minHeight: '100vh',
        background: bgColor ?? 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
      }}
    >
      <AppBar position="sticky" sx={{ backdropFilter: 'blur(8px)', background: 'rgba(0,0,0,0.45)' }} elevation={0}>
        <Toolbar>
          <Typography variant="h5" component="h1" fontWeight={700} letterSpacing={1}>
            🎵 Album Collection
          </Typography>
        </Toolbar>
      </AppBar>

      <Container maxWidth="xl" sx={{ py: 4 }}>
        {loading && (
          <Box sx={{ display: 'flex', justifyContent: 'center', py: 10 }}>
            <CircularProgress size={64} thickness={4} sx={{ color: 'white' }} />
          </Box>
        )}

        {!loading && error && (
          <Box sx={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 2, py: 6 }}>
            <Alert
              severity="error"
              sx={{ maxWidth: 480, width: '100%' }}
              action={
                <Button color="inherit" size="small" onClick={() => void fetchAlbums()}>
                  Retry
                </Button>
              }
            >
              {error}
            </Alert>
          </Box>
        )}

        {!loading && !error && (
          <Grid container spacing={3}>
            {albums.map((album) => (
              <Grid key={album.id} size={{ xs: 12, sm: 6, md: 4, lg: 3 }}>
                <AlbumCard album={album} />
              </Grid>
            ))}
          </Grid>
        )}
      </Container>
    </Box>
  )
}
